import type { IndustryCategory } from "@/lib/industry-taxonomy";
import type { ReviewFixture, ReviewRisk } from "@/lib/review-types";
import type { ReviewDetail, ReviewListItem, Risk } from "./types";

const reviewRisk = (risk: Risk | undefined): ReviewRisk => risk ? risk.charAt(0) + risk.slice(1).toLowerCase() as ReviewRisk : "Low";
const taxonomy = (value: string | undefined, sector: string | undefined, category: string | undefined, risk: Risk | undefined): IndustryCategory => ({ value: value ?? "", sector: sector ?? "Unclassified", category: category ?? "Unclassified", risk: risk ?? "LOW" });

export function toIndustryCategory(category: import("./types").TaxonomyCategory): IndustryCategory { return { value: category.taxonomy_value, sector: category.sector, category: category.category, risk: category.risk, taxonomyVersion: category.taxonomy_version }; }
export function toReviewFixture(review: ReviewDetail): ReviewFixture {
  const ai = taxonomy(review.ai_recommendation?.taxonomy_value ?? review.final_taxonomy_value, review.ai_recommendation?.sector ?? review.final_industry_sector, review.ai_recommendation?.category ?? review.final_industry_category, review.ai_recommendation?.risk ?? review.policy_risk);
  return { id: review.case_id, company: review.company_name ?? "Unnamed company", category: review.final_decision?.category ?? ai.category, risk: reviewRisk(review.final_decision?.risk ?? review.policy_risk), confidence: review.confidence === "HIGH" ? 90 : review.confidence === "MEDIUM" ? 70 : 50, status: review.review_status, authority: review.decision_authority, updated: review.last_updated_at, submitted: review.timestamp, documentName: review.source_pdf_filename, website: review.website, aiRecommendation: { ...ai, confidence: review.confidence === "HIGH" ? 90 : review.confidence === "MEDIUM" ? 70 : 50 }, proposedOverride: review.proposed_override ? { ...toIndustryCategory(review.proposed_override), reason: review.proposed_override.reason, notes: review.proposed_override.notes, submittedByRole: review.proposed_override.proposed_by_role, submittedAt: review.proposed_override.proposed_at } : undefined, approval: review.approval ? { required: review.approval.required, requiredRole: review.approval.required_role, status: review.approval.status, checkerRole: review.approval.checker_role, checkerAction: review.approval.checker_action?.toLowerCase() as "approved" | "rejected" | "modified" | undefined, checkerReason: review.approval.checker_reason, checkerAt: review.approval.checker_at } : { required: false, requiredRole: null, status: "NOT_REQUIRED" }, finalDecision: review.final_decision ? { ...toIndustryCategory(review.final_decision), decidedByRole: review.final_decision.finalized_by_role, decidedAt: review.final_decision.finalized_at, decisionSource: review.final_decision.decision_source } : undefined, workflowContext: review.workflow_context, history: review.history.map((event) => ({ id: event.event_id, time: event.event_timestamp, title: event.event_type, detail: event.event_detail ?? event.action_reason ?? "" })), allowedActions: review.allowed_actions, lastActionAt: review.last_updated_at, companySummary: review.company_summary, currentBusinessActivity: review.current_business_activity, futureOrPlannedActivity: review.future_or_planned_activity, evidence: review.evidence, materialCandidates: review.material_candidates, materialityUnclearCandidates: review.materiality_unclear_candidates, supportingCandidates: review.supporting_or_incidental_candidates, missingInformation: review.missing_information, conflictingInformation: review.conflicting_information, classificationCriticalGap: review.classification_critical_gap, classificationCriticalGapReason: review.classification_critical_gap_reason, confidenceReason: review.confidence_reason, tieResolution: review.tie_resolution, tieResolutionReason: review.tie_resolution_reason };
}
export function toQueueReview(review: ReviewListItem): ReviewFixture { const category = taxonomy(undefined, undefined, review.final_industry_category, review.policy_risk); const confidence = review.confidence === "HIGH" ? 90 : review.confidence === "MEDIUM" ? 70 : 50; return { id: review.case_id, company: review.company_name ?? "Unnamed company", category: category.category, risk: reviewRisk(review.policy_risk), confidence, status: review.review_status, authority: review.decision_authority, updated: review.last_updated_at, submitted: "", documentName: "", aiRecommendation: { ...category, confidence }, approval: { required: false, requiredRole: null, status: "NOT_REQUIRED" }, workflowContext: review.workflow_context, history: [], allowedActions: review.allowed_actions }; }
